portfolio mobile version
fahdrahali/portfolio pull request #1
Opened 2022-02-09 18:20 UTC by fahdrahali

**Create Portfolio mobile version using:**
- HTML
- CSS
- Responsive design
- FlexBox

2022-02-09 18:52 UTC, AnselemOdims requested changes
### Hi @fahdrahali, 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] Please make sure that your PR summary is properly written and descriptive. An example will be (Built out the HTML markup...)
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity!. You can tag me to your comments with @AnselemOdims for a quicker response.

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-02-09 18:52 UTC, AnselemOdims commented on index.html
> +        <h2 class="box">Hey there. I'm Fahd <br> <span class="second-title">I'm a software developer</span></h2>
- [ ] Kindly use the h1 tag for this sentence because it is the first heading tag in this section and that of the page. It is will also improve accessibility for screen readers

2022-02-09 18:52 UTC, AnselemOdims commented on index.html
> +    </section>
- [ ] Please include the list of icons as is specified in the original design. 
- [ ] Also, ensure that it looks almost identical to the original design by using the specified margins and paddings.

### Your design
![image](https://user-images.githubusercontent.com/43995830/153268075-630e2459-f1d4-4cc4-aafb-6491e4240618.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/153267974-63b0e2f0-bbf1-4d94-9507-b63d82a1ad8f.png)

2022-02-09 18:52 UTC, AnselemOdims commented on index.html
> +                <li><h2>Welcome</h2></li>
- [ ] Kindly make the 'Welcome' logo an anchor(a) tag instead of a h2 tag. This will enable users to click it and navigate to the homepage.

2022-02-09 23:20 UTC, BenMukebo requested changes
### Hi **@topaz,**

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻

- No linter errors. ✔️ 
- Githubflow was correctly used.  ✔️ 
- Good commit messages ✔️
 👍  Good job!

## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏 💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-10 08:11 UTC, AnselemOdims approved these changes
### Hi  @fahdrahali  🙋‍♀️, 
Good job in making the required changes 👏 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Use the tag @AnselemOdims for a quicker reply


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-10 08:18 UTC, merged